# Generated by Django 5.2 on 2025-09-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField()),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='logout', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Invalidado',
                'verbose_name_plural': 'Tokens Invalidados',
                'db_table': 'blacklisted_tokens',
                'indexes': [models.Index(fields=['jti'], name='blacklisted_jti_10baef_idx'), models.Index(fields=['user', 'blacklisted_at'], name='blacklisted_user_id_6f7037_idx')],
            },
        ),
    ]
