# Generated by Django 5.2 on 2025-09-04 19:14

import center.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_center',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[center.utils.validators.validate_registry_field], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='requesting_center',
            name='name',
            field=models.CharField(max_length=100, validators=[center.utils.validators.validate_registry_field], verbose_name='Nome'),
        ),
    ]
