# Generated by Django 5.2 on 2025-09-05 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_management_center_name_and_more'),
        ('sector', '0003_alter_coordination_name_alter_direction_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('coordination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.coordination', verbose_name='Coordenação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_hierarchies_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.direction', verbose_name='Direção')),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.management', verbose_name='Gerência')),
                ('management_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_associations', to='center.management_center', verbose_name='Centro Gestor')),
            ],
            options={
                'verbose_name': 'Associação Centro-Hierarquia',
                'verbose_name_plural': 'Associações Centro-Hierarquia',
                'indexes': [models.Index(fields=['direction'], name='center_cent_directi_c4f443_idx'), models.Index(fields=['management'], name='center_cent_managem_9d5f81_idx'), models.Index(fields=['coordination'], name='center_cent_coordin_6213da_idx'), models.Index(fields=['management_center'], name='center_cent_managem_b2964d_idx')],
                'unique_together': {('management_center', 'direction', 'management', 'coordination')},
            },
        ),
    ]
