# Generated by Django 5.2 on 2025-09-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_centerhierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management_center',
            name='description',
        ),
        migrations.RemoveField(
            model_name='requesting_center',
            name='description',
        ),
    ]
