# Generated by Django 5.2 on 2025-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_remove_description_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='management_center',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='requesting_center',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
