# Generated by Django 5.2.7 on 2025-12-30 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetline", "0002_budgetlineversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetline",
            name="budgeted_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Valor Orçado",
            ),
        ),
        migrations.AlterField(
            model_name="budgetlinemovement",
            name="movement_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Valor da Movimentação",
            ),
        ),
        migrations.AlterField(
            model_name="budgetlineversion",
            name="budgeted_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Valor Orçado",
            ),
        ),
    ]
