# Generated by Django 4.2.7 on 2024-01-26 12:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetmovement',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]