# Generated by Django 5.2 on 2025-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_fix_budgetmovement_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', 'category', 'management_center__name'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='budgetmovement',
            options={'ordering': ['-movement_date', '-created_at'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['year', 'category'], name='budget_budget_year_59a748_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['management_center', 'year'], name='budget_budget_manage_3b2f37_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status', 'year'], name='budget_budget_status_7db952_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['available_amount'], name='budget_budget_availab_4f6c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['-created_at'], name='budget_budget_created_8e9f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmovement',
            index=models.Index(fields=['source', 'movement_date'], name='budget_budge_source_58c1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmovement',
            index=models.Index(fields=['destination', 'movement_date'], name='budget_budge_destina_a1b9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmovement',
            index=models.Index(fields=['-movement_date'], name='budget_budge_movemen_c2e3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmovement',
            index=models.Index(fields=['amount'], name='budget_budge_amount_f5e6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmovement',
            index=models.Index(fields=['-created_at'], name='budget_budge_created_g8h9i0_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmovement',
            index=models.Index(fields=['source', 'destination'], name='budget_budge_source_j1k2l3_idx'),
        ),
    ]