# Generated by Django 5.2 on 2025-08-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_merge_fix_conflicts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', 'category'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='budgetmovement',
            options={'ordering': ['-movement_date'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='budget_budget_year_59a748_idx',
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='budget_budget_manage_3b2f37_idx',
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='budget_budget_status_7db952_idx',
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='budget_budget_availab_4f6c3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='budget_budget_created_8e9f8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetmovement',
            name='budget_budge_source_58c1a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetmovement',
            name='budget_budge_destina_a1b9f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetmovement',
            name='budget_budge_movemen_c2e3d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetmovement',
            name='budget_budge_amount_f5e6d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetmovement',
            name='budget_budge_created_g8h9i0_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetmovement',
            name='budget_budge_source_j1k2l3_idx',
        ),
    ]
