# Generated by Django 5.2.7 on 2025-12-30 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_alter_budget_options_alter_budgetmovement_options_and_more"),
        ("center", "0005_add_is_active_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["year"], name="budget_year_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["category"], name="budget_category_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["status"], name="budget_status_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["management_center"], name="budget_mgmt_center_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["year", "category"], name="budget_year_cat_idx"),
        ),
    ]
