# Dockerfile para DESENVOLVIMENTO
FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy project
COPY . .

EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]
