# Generated by Django 5.2.7 on 2025-12-30 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_alter_employee_status"),
        ("sector", "0004_coordination_is_active_direction_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["email"], name="employee_email_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["cpf"], name="employee_cpf_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["status"], name="employee_status_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["direction"], name="employee_direction_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["management"], name="employee_management_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["coordination"], name="employee_coordination_idx"
            ),
        ),
    ]
