# Generated by Django 5.2 on 2025-08-22 19:42

import sector.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='name',
            field=models.CharField(max_length=100, validators=[sector.utils.validators.validate_coordination_name], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[sector.utils.validators.validate_direction_name], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='management',
            name='name',
            field=models.CharField(max_length=100, validators=[sector.utils.validators.validate_management_name], verbose_name='Nome'),
        ),
    ]
