# Generated by Django 5.2 on 2025-05-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='management',
            name='description',
        ),
    ]
