# Generated by Django 5.2 on 2025-08-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0002_alter_coordination_name_alter_direction_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='management',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
