# Generated by Django 5.2 on 2025-10-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0003_alter_coordination_name_alter_direction_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordination',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='direction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='management',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
